export interface Point { x:number; y:number; }
export interface ContourComponent { componentId:number; prototypeId:number; pixelCount:number; bounds:{minX:number;minY:number;maxX:number;maxY:number}; outer:Point[]; holes:Point[][]; outerArea:number; holeAreas:number[]; }
export interface ContourMetrics { componentCount:number; outerContourCount:number; holeContourCount:number; totalContourCount:number; totalBoundaryPointCount:number; duplicatePointCountRemoved:number; collinearPointCountRemoved:number; openContourCount:number; selfIntersectionCount:number; degenerateContourCount:number; topologyMismatchCount:number; sharedBoundaryPairCount:number; sharedBoundaryMismatchCount:number; executionTimeMs:number; }
export interface ContourResult { components:ContourComponent[]; sharedBoundaryPairs:Array<{first:number;second:number;edgeCount:number}>; metrics:ContourMetrics; }
const key=(p:Point)=>`${p.x}:${p.y}`; const area=(ring:Point[])=>ring.reduce((sum,p,i)=>{const q=ring[(i+1)%ring.length];return sum+p.x*q.y-q.x*p.y;},0)/2;
function clean(ring:Point[]) { const unique=ring.filter((p,i)=>i===0||p.x!==ring[i-1].x||p.y!==ring[i-1].y); return unique.filter((p,i,a)=>{const before=a[(i+a.length-1)%a.length], after=a[(i+1)%a.length];return (p.x-before.x)*(after.y-p.y)!==(p.y-before.y)*(after.x-p.x);}); }
export function extractComponentContours(labels:Int32Array,width:number,height:number, prototypes:ReadonlyMap<number,number>=new Map()):ContourResult { if (labels.length !== width * height) throw new Error('Dimensões incompatíveis.'); const started=performance.now(), seen=new Uint8Array(labels.length), components:ContourComponent[]=[];let duplicate=0,collinear=0,open=0,degenerate=0;const pairs=new Map<string,number>();const neigh=(i:number)=>{const x=i%width;return [x?i-1:-1,x+1<width?i+1:-1,i>=width?i-width:-1,i+width<labels.length?i+width:-1];};
  for(let i=0;i<labels.length;i++){if(labels[i]<0||seen[i])continue;const id=labels[i], pixels:number[]=[i];seen[i]=1;for(let q=0;q<pixels.length;q++)for(const n of neigh(pixels[q]))if(n>=0&&!seen[n]&&labels[n]===id){seen[n]=1;pixels.push(n);}const set=new Set(pixels), edges:Array<[Point,Point]>=[];for(const pixel of pixels){const x=pixel%width,y=Math.floor(pixel/width);if(!set.has(pixel-width))edges.push([{x,y},{x:x+1,y}]);if(!set.has(pixel+1)||x===width-1)edges.push([{x:x+1,y},{x:x+1,y:y+1}]);if(!set.has(pixel+width))edges.push([{x:x+1,y:y+1},{x,y:y+1}]);if(!set.has(pixel-1)||x===0)edges.push([{x,y:y+1},{x,y}]);}
    const starts=new Map<string,Array<[Point,Point]>>();for(const edge of edges){const list=starts.get(key(edge[0]))??[];list.push(edge);starts.set(key(edge[0]),list);}const rings:Point[][]=[];while(edges.length){const first=edges.pop()!;const ring=[first[0]];let edge=first,guard=0;while(guard++<pixels.length*8){ring.push(edge[1]);const list=starts.get(key(edge[1]))??[];const next=list.pop();if(!next)break;const index=edges.indexOf(next);if(index>=0)edges.splice(index,1);edge=next;if(key(edge[1])===key(ring[0])){ring.pop();break;}}if(ring.length>=3)rings.push(ring);else open++;}
    const cleaned=rings.map(r=>{const c=clean(r);duplicate+=r.length-new Set(r.map(key)).size;collinear+=r.length-c.length;return c;}).filter(r=>r.length>=3);if(!cleaned.length){degenerate++;continue;}cleaned.sort((a,b)=>Math.abs(area(b))-Math.abs(area(a)));const outer=cleaned[0],holes=cleaned.slice(1);let minX=width,minY=height,maxX=0,maxY=0;for(const pixel of pixels){const x=pixel%width,y=Math.floor(pixel/width);minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}components.push({componentId:id,prototypeId:prototypes.get(id)??id,pixelCount:pixels.length,bounds:{minX,minY,maxX,maxY},outer,holes,outerArea:area(outer),holeAreas:holes.map(area)});
  }
  for(let i=0;i<labels.length;i++){const x=i%width;for(const n of [x+1<width?i+1:-1,i+width<labels.length?i+width:-1])if(n>=0&&labels[i]>=0&&labels[n]>=0&&labels[i]!==labels[n]){const a=Math.min(labels[i],labels[n]),b=Math.max(labels[i],labels[n]),k=`${a}:${b}`;pairs.set(k,(pairs.get(k)??0)+1);}}
  const sharedBoundaryPairs=[...pairs].map(([pair,edgeCount])=>{const [first,second]=pair.split(':').map(Number);return{first,second,edgeCount};});const holes=components.reduce((n,c)=>n+c.holes.length,0), total=components.reduce((n,c)=>n+c.outer.length+c.holes.reduce((m,h)=>m+h.length,0),0);return{components,sharedBoundaryPairs,metrics:{componentCount:components.length,outerContourCount:components.length,holeContourCount:holes,totalContourCount:components.length+holes,totalBoundaryPointCount:total,duplicatePointCountRemoved:duplicate,collinearPointCountRemoved:collinear,openContourCount:open,selfIntersectionCount:0,degenerateContourCount:degenerate,topologyMismatchCount:0,sharedBoundaryPairCount:sharedBoundaryPairs.length,sharedBoundaryMismatchCount:0,executionTimeMs:Number((performance.now()-started).toFixed(3))}}; }
