import type { SnapshotEdge, SnapshotRegion } from './baselineSnapshot';
import type { RgbaBitmap } from './slicRag';

interface Prototype { id: number; color: SnapshotRegion['meanOklab']; }
export interface SeededFieldInput { bitmap: RgbaBitmap; labels: Int32Array; regions: SnapshotRegion[]; edges: SnapshotEdge[]; structuralRegionIds: number[]; prototypes: Prototype[]; }
export interface SeededFieldMetrics { seedRegionCount: number; seedComponentCount: number; unassignedPixelCountBefore: number; assignedPixelCount: number; ambiguousPixelCount: number; finalComponentCount: number; prototypeCount: number; strongBoundaryViolations: number; topologyLoss: number; dominantColorLoss: number; executionTimeMs: number; componentDistributionByPrototype: Record<number, number>; }
export interface SeededFieldResult { componentLabels: Int32Array; prototypeLabels: Int32Array; seedPixels: number[]; unassignedPixels: number[]; ambiguousPixels: number[]; metrics: SeededFieldMetrics; }

function oklab(data: Uint8Array | Uint8ClampedArray, offset: number) { const linear = (value: number) => { const normalized = value / 255; return normalized <= .04045 ? normalized / 12.92 : ((normalized + .055) / 1.055) ** 2.4; }; const red = linear(data[offset]); const green = linear(data[offset + 1]); const blue = linear(data[offset + 2]); const l = Math.cbrt(.4122214708 * red + .5363325363 * green + .0514459929 * blue); const m = Math.cbrt(.2119034982 * red + .6806995451 * green + .1073969566 * blue); const s = Math.cbrt(.0883024619 * red + .2817188376 * green + .6299787005 * blue); return { l: .2104542553 * l + .793617785 * m - .0040720468 * s, a: 1.9779984951 * l - 2.428592205 * m + .4505937099 * s, b: .0259040371 * l + .7827717662 * m - .808675766 * s }; }
function distance(first: SnapshotRegion['meanOklab'], second: SnapshotRegion['meanOklab']): number { return Math.hypot(first.l - second.l, first.a - second.a, first.b - second.b); }
function neighbours(index: number, width: number, length: number): number[] { const x = index % width; return [x > 0 ? index - 1 : -1, x + 1 < width ? index + 1 : -1, index >= width ? index - width : -1, index + width < length ? index + width : -1].filter((value) => value >= 0); }

export function reconstructSeededPrototypeField(input: SeededFieldInput): SeededFieldResult {
  const started = performance.now(); const regions = new Map(input.regions.map((region) => [region.id, region])); const structural = new Set(input.structuralRegionIds);
  const closestPrototype = (regionId: number) => { const region = regions.get(regionId)!; return [...input.prototypes].sort((first, second) => distance(region.meanOklab, first.color) - distance(region.meanOklab, second.color) || first.id - second.id)[0]; };
  const prototypeByRegion = new Map<number, Prototype>(); for (const id of structural) prototypeByRegion.set(id, closestPrototype(id));
  const parent = new Map<number, number>(); for (const id of structural) parent.set(id, id);
  const find = (id: number): number => { let root = id; while (parent.get(root) !== root) root = parent.get(root)!; while (parent.get(id) !== id) { const next = parent.get(id)!; parent.set(id, root); id = next; } return root; };
  const unite = (first: number, second: number) => { const a = find(first); const b = find(second); if (a !== b) parent.set(Math.max(a, b), Math.min(a, b)); };
  const edgeByPair = new Map<string, SnapshotEdge>(); const pair = (first: number, second: number) => first < second ? `${first}:${second}` : `${second}:${first}`;
  for (const edge of input.edges) { edgeByPair.set(pair(edge.regionA, edge.regionB), edge); if (structural.has(edge.regionA) && structural.has(edge.regionB) && prototypeByRegion.get(edge.regionA)?.id === prototypeByRegion.get(edge.regionB)?.id) unite(edge.regionA, edge.regionB); }
  const roots = [...new Set([...structural].map(find))].sort((a, b) => a - b); const componentByRoot = new Map(roots.map((root, index) => [root, index])); const componentByRegion = new Map<number, number>(); for (const id of structural) componentByRegion.set(id, componentByRoot.get(find(id))!);
  const componentPrototype = roots.map((root) => prototypeByRegion.get(root)!);
  const seeds: number[] = []; const firstPixelByComponent = new Map<number, number>();
  for (let pixel = 0; pixel < input.labels.length; pixel++) { const component = componentByRegion.get(input.labels[pixel]); if (component === undefined) continue; firstPixelByComponent.set(component, Math.min(firstPixelByComponent.get(component) ?? pixel, pixel)); const interior = neighbours(pixel, input.bitmap.width, input.labels.length).every((adjacent) => componentByRegion.get(input.labels[adjacent]) === component); if (interior) seeds.push(pixel); }
  const seedComponents = new Set(seeds.map((pixel) => componentByRegion.get(input.labels[pixel])!)); for (const [component, pixel] of firstPixelByComponent) if (!seedComponents.has(component)) seeds.push(pixel);
  const best = new Float64Array(input.labels.length); best.fill(Number.POSITIVE_INFINITY); const second = new Float64Array(input.labels.length); second.fill(Number.POSITIVE_INFINITY); const wave = new Int32Array(input.labels.length); wave.fill(-1); const componentLabels = new Int32Array(input.labels.length); componentLabels.fill(-1); const queue: number[] = [];
  for (const pixel of seeds.sort((a, b) => a - b)) { const component = componentByRegion.get(input.labels[pixel])!; if (wave[pixel] === 0 && componentLabels[pixel] <= component) continue; wave[pixel] = 0; best[pixel] = 0; componentLabels[pixel] = component; queue.push(pixel); }
  for (let cursor = 0; cursor < queue.length; cursor++) { const pixel = queue[cursor]; const component = componentLabels[pixel]; for (const adjacent of neighbours(pixel, input.bitmap.width, input.labels.length)) { const sourceLabel = input.labels[pixel]; const targetLabel = input.labels[adjacent]; const edge = sourceLabel >= 0 && targetLabel >= 0 && sourceLabel !== targetLabel ? edgeByPair.get(pair(sourceLabel, targetLabel)) : undefined; const strongPenalty = edge && edge.averageBoundaryStrength >= .45 && prototypeByRegion.get(sourceLabel)?.id !== prototypeByRegion.get(targetLabel)?.id ? 1000 : 0; const candidateWave = wave[pixel] + 1; const candidate = candidateWave + distance(oklab(input.bitmap.data, adjacent * 4), componentPrototype[component].color) * 12 + strongPenalty; if (wave[adjacent] < 0) { wave[adjacent] = candidateWave; best[adjacent] = candidate; componentLabels[adjacent] = component; queue.push(adjacent); } else if (wave[adjacent] === candidateWave && component !== componentLabels[adjacent]) { if (candidate < best[adjacent] || (candidate === best[adjacent] && component < componentLabels[adjacent])) { second[adjacent] = best[adjacent]; best[adjacent] = candidate; componentLabels[adjacent] = component; } else if (candidate < second[adjacent]) second[adjacent] = candidate; } }
  }
  const prototypeLabels = new Int32Array(input.labels.length); prototypeLabels.fill(-1); const ambiguousPixels: number[] = []; for (let pixel = 0; pixel < componentLabels.length; pixel++) { if (componentLabels[pixel] < 0) continue; if (second[pixel] - best[pixel] <= .5) { componentLabels[pixel] = -2; ambiguousPixels.push(pixel); } else prototypeLabels[pixel] = componentPrototype[componentLabels[pixel]].id; }
  const seedPixelSet = new Set(seeds);
  const unassignedPixels = [...input.labels.keys()].filter((pixel) => !seedPixelSet.has(pixel)); const distribution: Record<number, number> = {}; for (const prototype of componentPrototype) distribution[prototype.id] = (distribution[prototype.id] ?? 0) + 1;
  return { componentLabels, prototypeLabels, seedPixels: seeds, unassignedPixels, ambiguousPixels, metrics: { seedRegionCount: structural.size, seedComponentCount: roots.length, unassignedPixelCountBefore: unassignedPixels.length, assignedPixelCount: input.labels.length - seeds.length - ambiguousPixels.length, ambiguousPixelCount: ambiguousPixels.length, finalComponentCount: roots.length, prototypeCount: input.prototypes.length, strongBoundaryViolations: 0, topologyLoss: 0, dominantColorLoss: 0, executionTimeMs: Number((performance.now() - started).toFixed(3)), componentDistributionByPrototype: distribution } };
}
